////////////////////////////////////////////////////////////////////////
//
// StdAfx.h
//
// This file was generated by XMLSpy 2011r3sp1 Enterprise Edition.
//
// YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
// OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
//
// Refer to the XMLSpy Documentation for further details.
// http://www.altova.com/xmlspy
//
////////////////////////////////////////////////////////////////////////

#pragma once
#ifndef cutting_tool_schema_armTest_STDAFX_H_INCLUDED
#define cutting_tool_schema_armTest_STDAFX_H_INCLUDED

#if _MSC_VER < 1300
#pragma warning ( disable : 4786 )	// identifier was truncated to '255' characters in the debug information
#endif

#if !defined( __GNUC__ )

#include <tchar.h>
#include <windows.h>

#endif


//#import "msxml6.dll" named_guids no_implementation




#include "../Altova/Altova.h"
#include "../Altova/SchemaTypes.h"
#include "../Altova/AltovaException.h"

#include "../AltovaXML/XmlException.h"
#include "../AltovaXML/Node.h"

using namespace altova;


//{{AFX_INSERT_LOCATION}}

#endif // cutting_tool_schema_armTest_STDAFX_H_INCLUDED
